"use client";

import "bootstrap/dist/css/bootstrap.min.css";
import "admin-lte/dist/css/adminlte.min.css";
import "admin-lte/plugins/fontawesome-free/css/all.min.css";
import "./globals.css";
import Loading from "./loading";
import { useAuthStore } from "@/store/auth";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const loading = useAuthStore((state) => state.loading);

  function renderConditionally() {
    if (loading) {
      return <Loading />;
    }

    return children;
  }

  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Integração ViaCEP</title>
      <meta name="description" content="Generated by create next app" />
      <body>{renderConditionally()}</body>
    </html>
  );
}
